name: dcli_core
version: 4.0.1-beta.4
homepage: https://dcli.onepub.dev
documentation: https://dcli.onepub.dev
description: The core asyncronous functions used by dcli. DCli uses waitFor to eliminate async code in the DCli libraries which precludes DCli's usage in non-cli apps (e.g. you can't use it in flutter). The aim of dcli_core is to expose a significant set of the core dcli functions as async version so that dcli_core can be used in any project. DCli will then rely on dcli_core for core parts of its implemenation to avoid duplicating code between the two packages.
repository: https://github.com/onepub-dev/dcli
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  async: ^2.11.0
  circular_buffer: ^0.11.0
  collection: ^1.18.0
  crypto: ^3.0.3
  ffi: ^2.1.2
  logging: ^1.2.0
  meta: ">=1.11.0 <2.0.0"
  path: ^1.9.0
  scope: ^4.1.0
  stack_trace: ^1.11.1
  uuid: ^4.4.0
  dcli_common:

dev_dependencies:
  lint_hard: ^4.0.0
  synchronized: ^3.1.0+1
  test: ^1.25.3
platforms:
  android:
  ios:
  linux:
  macos:
  windows:
