name: dcli_test
description: Test code used by dcli - not for general use.
version: 4.0.1-beta.4
repository: https://github.com/onepub-dev/dcli/tree/master/dcli_test

environment:
  sdk: '>=3.2.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  file: ^7.0.0
  meta: ">=1.11.0 <2.0.0"
  path: ^1.9.0
  scope: ^4.1.0
  stack_trace: ^1.11.1
  test: ^1.25.4
  uuid: ^4.4.0
  dcli:
  dcli_common:
  dcli_core:
  runtime_named_locks:

dev_dependencies:
  lints: ^3.0.0
