name: dcli_test
description: Test code used by dcli - not for general use.
version: 4.0.1-alpha.10
repository: https://github.com/onepub-dev/dcli/tree/master/dcli_test

environment:
  sdk: '>=3.2.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  file: ^7.0.0
  meta: ^1.12.0
  path: ^1.9.0
  scope: ^4.1.0
  stack_trace: ^1.11.1
  test: ^1.25.2
  uuid: ^4.3.3
  dcli:
  dcli_common:
  dcli_core:

dev_dependencies:
  lints: ^3.0.0
