name: dcli_unit_tester
version: 4.0.0
description: This project allows dcli to unit test functions that behave differently when installed via 'dart pub global activate'. It serves no other useful purpose so do not install!
repository: https://github.com/noojee/dcli
environment:
  sdk: '>=3.3.0 <4.5.0'
dependencies:
  args: ^2.5.0
  path: ^1.9.0
  dcli:
  dcli_core:
  dcli_terminal:
dev_dependencies:
  lint_hard: ^4.0.0
executables:
  dcli_unit_tester:
