name: tool/run_unit_tests.dart

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        sdk: [stable, beta, dev, 2.16.0, 2.17.0]

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3

      - name: Install dependencies
        run: |
          cd dcli_core
          dart pub get
          cd ../dcli
          dart pub get
          cd ..

      - name: run unit tests
        run: |
          cd dcli
          dart pub global activate -spath .
          dart test
          
          
