name: Release executables for Windows

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    #container:
     # image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Fetch Dart SDK
      run: curl https://storage.googleapis.com/dart-archive/channels/stable/release/2.8.4/sdk/dartsdk-windows-x64-release.zip -o dartsdk.zip 
    - name: Extract Dart sDK
      run: tar.exe -xf dartsdk.zip
    
    - name: setup paths
      run: $Env:Path += ";C:\tools\dart-sdk;${HOME}/.pub-cache/bin;${HOME}/.dcli/bin"
    - name: create working dir
      run: mkdir ../pub_release
      
    - name: clone pub_release
      # run: pub global activate pub_release
      run:  git clone https://github.com/bsutton/pub_release.git
      working-directory: ..
      
    - name: activate pub_release
      run: dart pub global activate pub_release --source=path
      working-directory: ..
      
    - name: activate dcli
      run: dart pub global activate dcli --source=path
      working-directory: ..
      
      
    - name: Create release
      env:
        APITOKEN:  ${{ secrets.APITOKEN }}
      run: git_release --username bsutton --apiToken "$APITOKEN" --owner bsutton --repository dcli --suffix windows
  
