name: dcli
version: 4.0.1-alpha.10
homepage: https://dcli.onepub.dev
documentation: https://dcli.onepub.dev
description: Dart console SDK - write console (cli) apps/scripts using dart.
repository: https://github.com/onepub-dev/dcli
environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  archive: ^3.4.10
  args: ^2.4.2
  async: ^2.11.0
  chunked_stream: ^1.4.2
  collection: ^1.18.0
  convert: ^3.1.1
  crypto: ^3.0.3
  csv: ^6.0.0
  equatable: ^2.0.5
  ffi: ^2.1.2
  file: ^7.0.0
  glob: ^2.1.2
  ini: ^2.1.0
  logging: ^1.2.0
  meta: ^1.12.0
  mime: ^1.0.5
  path: ^1.9.0
  posix: ^6.0.1
  pub_semver: ^2.1.4
  pubspec_lock: ^3.0.2
  pubspec_manager: ^1.0.0-beta.1
  scope: ^4.1.0
  stack_trace: ^1.11.1
  uuid: ^4.3.3
  validators2: ^5.0.0
  win32: ^5.3.0
  yaml: ^3.1.2
  #  Overridden with MELOS
  settings_yaml:
    path: ../../settings_yaml
  dcli_common:
    path: ../dcli_common
  dcli_core:
    path: ../dcli_core
  dcli_terminal:
    path: ../dcli_terminal
  system_info:
    path: ../../system_info
  dart_console:
    path: ../../dart_console
dev_dependencies:
  dcli_test:
    path: ../dcli_test
  hex: ^0.2.0
  lint_hard: ^4.0.0
  mocktail: ^1.0.3
  test: ^1.25.2
  test_api: ^0.7.0
  test_core: ^0.6.0
executables:
  dcli:
platforms:
  linux:
  macos:
  windows:
