name: dcli_common
version: 4.0.1-beta.2
description: Common code used by multiple dcli packages.
repository: https://github.com/open-runtime/dcli-4.x.git
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  meta: ">=1.11.0 <2.0.0"
  path: ^1.9.0
  scope: ^4.1.0
dev_dependencies:
  lint_hard: ^4.0.0
  test: ^1.25.3
