name: since
version: 0.0.1
description: A since command-line application created by dcli
environment: 
  sdk: '>=3.0.0 <4.0.0'
dependencies: 
  stack_trace: ^1.10.0
  dcli:
dev_dependencies:
  lint_hard: ^4.0.0
