name: (Shared) DCLI Unit Tests

on:
  workflow_call:
    inputs:
      matrix-config:
        description: 'The Matrix as a JSON String to be used for the Matrix Strategy'
        required: true
        type: string

jobs:
  compose:
    name: ${{ matrix.config.name }} Composition
    runs-on: ${{ matrix.config.runner }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - ${{ fromJSON(inputs.matrix-config) }}

    env:
      GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3

      - name: Echo Default Cache Paths
        if: matrix.config.system_information.kernel_family == 'unix'
        env:
          DART_SDK_DIR_DEFAULT: /opt/hostedtoolcache/dart-sdk/
          HOME_BREW_DIR_DEFAULT: /usr/local
          DCLI_BIN_DIR_DEFAULT: .dcli/bin/
          PUB_CACHE_DIR_DEFAULT: .pub-cache/
        run: |
          echo "HOME_BREW_DIR=$(command -v brew >/dev/null 2>&1 && echo "$(brew --prefix)" || echo $HOME_BREW_DIR_DEFAULT)" >> $GITHUB_ENV
          echo "DCLI_BIN_DIR=$HOME/${DCLI_BIN_DIR_DEFAULT}" >> $GITHUB_ENV
          echo "PUB_CACHE_DIR=$HOME/${PUB_CACHE_DIR_DEFAULT}" >> $GITHUB_ENV
          echo "DART_SDK_DIR=$(echo $DART_SDK_DIR_DEFAULT)" >> $GITHUB_ENV

      - name: Echo Default Cache Paths [Windows]
        if: matrix.config.system_information.operating_system_family == 'windows'
        env:
          DART_SDK_DIR_DEFAULT: C:\tools\dart-sdk\bin
        run: |
          echo "DART_SDK_DIR=$($env:DART_SDK_DIR_DEFAULT)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          
          $program_files = $env:ProgramFiles
          $dcli_bin_dir = Join-Path -Path $program_files -ChildPath "\.dcli\bin"
          echo "DCLI_BIN_DIR=$dcli_bin_dir" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "PUB_CACHE_DIR=$env:USERPROFILE\.pub-cache\" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Echo Initial Cache Locations
        run: |
          echo 'DART_SDK_DIR: ${{ env.DART_SDK_DIR }}'
          echo 'DCLI_BIN_DIR: ${{ env.DCLI_BIN_DIR }}'
          echo 'PUB_CACHE_DIR: ${{ env.PUB_CACHE_DIR }}'

      - name: Run Pub Get
        run: |
          cd ./dcli && dart pub get
          cd ../dcli_common && dart pub get
          cd ../dcli_core && dart pub get
          cd ../dcli_sdk && dart pub get
          cd ../dcli_input && dart pub get
          cd ../dcli_terminal && dart pub get
          cd ../dcli_test && dart pub get
          cd ../dcli_unit_tester && dart pub get
          cd ../

      - name: Compile AOTs for DCLI on Unix
        run: |
          dart compile exe ./dcli_sdk/bin/dcli.dart -o ./dcli_sdk/bin/dcli
          dart compile exe ./dcli_sdk/bin/dcli_complete.dart -o ./dcli_sdk/bin/dcli_complete
          dart compile exe ./dcli_sdk/bin/dcli_install.dart -o ./dcli_sdk/bin/dcli_install

      - name: Activate DCLI Globally from Local SDK Path
        run: |
          dart pub global activate -spath ./dcli_sdk --overwrite

      - name: Move AOTs to Dart Pub Cache
        run: |
          local PUB_CACHE_BIN_DIR=$PUB_CACHE_DIR/bin
          mv ./dcli_sdk/bin/dcli $PUB_CACHE_BIN_DIR
          mv ./dcli_sdk/bin/dcli_complete $PUB_CACHE_BIN_DIR
          mv ./dcli_sdk/bin/dcli_install $PUB_CACHE_BIN_DIR

      - name: List DCLI Binaries in Pub Cache Bin
        run: |
          ls -la $PUB_CACHE_BIN_DIR
          command -v dcli >/dev/null && echo "✅ Available and Globally Installed dcli" || echo "⛔️dcli not found in PATH. Check if it is installed correctly." && command -v dcli_complete >/dev/null && echo "✅ Available and Globally Installed dcli_complete" || echo "⛔️dcli_complete not found in PATH. Check if it is installed correctly." && command -v dcli_install >/dev/null && echo "✅ Available and Globally Installed dcli_install" || echo "⛔️dcli_install not found in PATH. Check if it is installed correctly."
          which dcli
          which dcli_install
          which dcli_complete

      - name: Run DCLI Install
        run: |
          sudo env "PATH=$PATH" dcli -v install

#      - name: Run Unit Tests for synchronous_test.dart
#        run: cd ./dcli && dart test ./test/src/process/process/synchronous_test.dart && cd ../
